name: Check for updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'True to force sync / generate dependency manifests'
        type: boolean
        required: true
        default: false
env:
  CLOJURE_VERSION: '1.10.1.763'
  NODE_VERSION: '16'
jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      up_to_date: ${{ steps.check-update.outputs.up_to_date }}
    steps:
      - id: check-update
        run: ./00-check-update.sh
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    needs: [ check-update ]
    if: ${{ !needs.check-update.outputs.up_to_date || inputs.force }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install python and pix
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Java SDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Setup clojure
        run: |
          curl -O -L https://download.clojure.org/install/linux-install-1.10.1.763.sh
          sha256sum -c - <<HERE
          91421551872d421915c4a598741aefcc6749d3f4aafca9c08f271958e5456e2c linux-install-1.10.1.763.sh
          HERE
          sh linux-install-1.10.1.763.sh
      - name: Install flatpak-node-generator
        run: pipx install "git+https://github.com/flatpak/flatpak-builder-tools.git#egg=subdir&subdirectory=node"
      - name: Generate dependency manifests
        run: ./01-sync-release.sh
      # - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
      #   env:
      #     GIT_AUTHOR_NAME: Flatpak External Data Checker
      #     GIT_COMMITTER_NAME: Flatpak External Data Checker
      #     GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      #     GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      #     EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     args: --update --never-fork com.logseq.Logseq.yml
